networks:
  default:
  traefik:
    external: true

services:
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./volumes/redis:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/usr/src/paperless/data
      - ./volumes/media:/usr/src/paperless/media
      - ./volumes/export:/usr/src/paperless/export
      - ./volumes/consume:/usr/src/paperless/consume
    env_file:
      - ../${ENV_FILE}
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

      PAPERLESS_URL: https://${PAPERLESS_DOMAIN}

      PAPERLESS_SOCIAL_AUTO_SIGNUP: True
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect

      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "${PAPERLESS_OIDC_NAME}",
                "client_id": "${PAPERLESS_OIDC_CLIENT_ID}",
                "secret": "${PAPERLESS_OIDC_SECRET}",
                "settings": {
                  "server_url": "${PAPERLESS_OIDC_SERVER_URL}"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }

    depends_on:
      - db
      - redis
      - gotenberg
      - tika
    # ports:
    #   - "8000:8000"
    networks:
    - traefik
    - default

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`${PAPERLESS_DOMAIN}`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
